version: '3.8'

services:
  flight-service:
    build: ./FlightMicroservice
    ports:
      - "8081:8084"  # Host:Container

  ticket-service:
    build: ./TicketMicroservice
    ports:
      - "8082:8084"

  user-service:
    build: ./UserMicroservice
    ports:
      - "8083:8084"

  api-gateway:
    build: ./ApiGatewayService
    ports:
      - "8080:8084"
    depends_on:
      - flight-service
      - ticket-service
      - user-service
