server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: flight-service
          uri: http://localhost:8082
          predicates:
            - Path=/flight/**
        - id: ticket-service
          uri: http://localhost:8083
          predicates:
            - Path=/ticket/**